const fs = require('fs');
const path = require('path');

const schemaLines = [
  'generator client {',
  '  provider = "prisma-client-js"',
  '}',
  '',
  'datasource db {',
  '  provider = "postgresql"',
  '  url      = env("DATABASE_URL")',
  '}',
  '',
  'enum MerchantStatus {',
  '  ACTIVE',
  '  INACTIVE',
  '  SUSPENDED',
  '}',
  '',
  'enum MerchantType {',
  '  BEAUTY',
  '  FITNESS',
  '  EDUCATION',
  '  CONSULTING',
  '  REPAIR',
  '  RETAIL',
  '  GENERIC',
  '}',
  '',
  'enum UserRole {',
  '  OWNER',
  '  STAFF',
  '  VIEWER',
  '}',
  '',
  'enum UserStatus {',
  '  ACTIVE',
  '  INACTIVE',
  '  BANNED',
  '}',
  '',
  'enum ServiceType {',
  '  SERVICE',
  '  PRODUCT',
  '  PACKAGE',
  '}',
  '',
  'enum ServiceStatus {',
  '  ACTIVE',
  '  INACTIVE',
  '  DRAFT',
  '}',
  '',
  'enum OrderStatus {',
  '  DRAFT',
  '  PENDING_PAYMENT',
  '  PENDING_APPROVAL',
  '  APPROVED',
  '  COMPLETED',
  '  FAILED',
  '  CANCELLED',
  '  REFUNDED',
  '}',
  '',
  'enum PaymentStatus {',
  '  PENDING',
  '  APPROVED',
  '  COMPLETED',
  '  FAILED',
  '  CANCELLED',
  '  REFUNDED',
  '}',
  '',
  'enum BookingStatus {',
  '  PENDING',
  '  CONFIRMED',
  '  COMPLETED',
  '  CANCELLED',
  '  NO_SHOW',
  '}',
  '',
  'enum MembershipMode {',
  '  TIME_BASED',
  '  USAGE_BASED',
  '  UNLIMITED',
  '}',
  '',
  'enum MembershipStatus {',
  '  ACTIVE',
  '  EXPIRED',
  '  CANCELLED',
  '}',
  '',
  'enum CheckoutMode {',
  '  SINGLE',
  '  SUBSCRIPTION',
  '}',
  '',
  'model Merchant {',
  '  id           String         @id @default(cuid())',
  '  name         String',
  '  type         MerchantType   @default(GENERIC)',
  '  status       MerchantStatus @default(ACTIVE)',
  '  logo         String?',
  '  contactName  String?        @map("contact_name")',
  '  contactPhone String?        @map("contact_phone")',
  '  themeConfig  Json?          @map("theme_config")',
  '  createdAt    DateTime       @default(now()) @map("created_at")',
  '  updatedAt    DateTime       @updatedAt @map("updated_at")',
  '',
  '  merchantUsers MerchantUser[]',
  '  customers     Customer[]',
  '  services      Service[]',
  '  orders        Order[]',
  '  bookings      Booking[]',
  '  memberships   Membership[]',
  '  appConfig     AppConfig?',
  '',
  '  @@map("merchants")',
  '}',
  '',
  'model MerchantUser {',
  '  id         String     @id @default(cuid())',
  '  merchantId String     @map("merchant_id")',
  '  piUid      String     @map("pi_uid")',
  '  username   String',
  '  role       UserRole   @default(STAFF)',
  '  status     UserStatus @default(ACTIVE)',
  '  createdAt  DateTime   @default(now()) @map("created_at")',
  '',
  '  merchant Merchant @relation(fields: [merchantId], references: [id], onDelete: Cascade)',
  '',
  '  @@index([merchantId])',
  '  @@index([piUid])',
  '  @@map("merchant_users")',
  '}',
  '',
  'model Customer {',
  '  id               String   @id @default(cuid())',
  '  merchantId       String   @map("merchant_id")',
  '  piUid            String   @map("pi_uid")',
  '  username         String',
  '  displayName      String?  @map("display_name")',
  '  membershipStatus MembershipStatus? @map("membership_status")',
  '  createdAt        DateTime @default(now()) @map("created_at")',
  '',
  '  merchant           Merchant             @relation(fields: [merchantId], references: [id], onDelete: Cascade)',
  '  orders             Order[]',
  '  bookings           Booking[]',
  '  customerMemberships CustomerMembership[]',
  '',
  '  @@index([merchantId])',
  '  @@index([piUid])',
  '  @@unique([merchantId, piUid])',
  '  @@map("customers")',
  '}',
  '',
  'model Service {',
  '  id              String        @id @default(cuid())',
  '  merchantId      String        @map("merchant_id")',
  '  type            ServiceType   @default(SERVICE)',
  '  title           String',
  '  description     String?',
  '  price           Decimal       @db.Decimal(10, 2)',
  '  durationMinutes Int?          @map("duration_minutes")',
  '  status          ServiceStatus @default(ACTIVE)',
  '  createdAt       DateTime      @default(now()) @map("created_at")',
  '',
  '  merchant Merchant  @relation(fields: [merchantId], references: [id], onDelete: Cascade)',
  '  orders   Order[]',
  '  bookings Booking[]',
  '',
  '  @@index([merchantId])',
  '  @@index([merchantId, status])',
  '  @@map("services")',
  '}',
  '',
  'model Order {',
  '  id         String      @id @default(cuid())',
  '  merchantId String      @map("merchant_id")',
  '  customerId String      @map("customer_id")',
  '  serviceId  String?     @map("service_id")',
  '  orderNo    String      @unique @map("order_no")',
  '  amount     Decimal     @db.Decimal(10, 2)',
  '  currency   String      @default("PI")',
  '  status     OrderStatus @default(DRAFT)',
  '  paymentId  String?     @map("payment_id")',
  '  note       String?',
  '  createdAt  DateTime    @default(now()) @map("created_at")',
  '  updatedAt  DateTime    @updatedAt @map("updated_at")',
  '',
  '  merchant   Merchant   @relation(fields: [merchantId], references: [id])',
  '  customer   Customer   @relation(fields: [customerId], references: [id])',
  '  service    Service?   @relation(fields: [serviceId], references: [id])',
  '  payments   Payment[]',
  '',
  '  @@index([merchantId])',
  '  @@index([customerId])',
  '  @@index([status])',
  '  @@index([merchantId, status])',
  '  @@map("orders")',
  '}',
  '',
  'model Payment {',
  '  id                    String        @id @default(cuid())',
  '  orderId               String        @map("order_id")',
  '  piPaymentId           String        @unique @map("pi_payment_id")',
  '  txid                  String?       @unique',
  '  amount                Decimal       @db.Decimal(10, 2)',
  '  memo                  String?',
  '  status                PaymentStatus @default(PENDING)',
  '  developerApproved     Boolean       @default(false) @map("developer_approved")',
  '  transactionVerified   Boolean       @default(false) @map("transaction_verified")',
  '  developerCompleted    Boolean       @default(false) @map("developer_completed")',
  '  userCancelled         Boolean       @default(false) @map("user_cancelled")',
  '  createdAt             DateTime      @default(now()) @map("created_at")',
  '  approvedAt            DateTime?     @map("approved_at")',
  '  completedAt           DateTime?     @map("completed_at")',
  '',
  '  order Order @relation(fields: [orderId], references: [id])',
  '',
  '  @@index([orderId])',
  '  @@index([status])',
  '  @@index([piPaymentId])',
  '  @@map("payments")',
  '}',
  '',
  'model Booking {',
  '  id         String        @id @default(cuid())',
  '  merchantId String        @map("merchant_id")',
  '  customerId String        @map("customer_id")',
  '  serviceId  String?       @map("service_id")',
  '  slotStart  DateTime      @map("slot_start")',
  '  slotEnd    DateTime      @map("slot_end")',
  '  status     BookingStatus @default(PENDING)',
  '  note       String?',
  '  createdAt  DateTime      @default(now()) @map("created_at")',
  '',
  '  merchant Merchant @relation(fields: [merchantId], references: [id])',
  '  customer Customer @relation(fields: [customerId], references: [id])',
  '  service  Service? @relation(fields: [serviceId], references: [id])',
  '',
  '  @@index([merchantId])',
  '  @@index([customerId])',
  '  @@index([merchantId, slotStart])',
  '  @@index([status])',
  '  @@map("bookings")',
  '}',
  '',
  'model Membership {',
  '  id           String         @id @default(cuid())',
  '  merchantId   String         @map("merchant_id")',
  '  name         String',
  '  mode         MembershipMode',
  '  price        Decimal        @db.Decimal(10, 2)',
  '  validDays    Int?           @map("valid_days")',
  '  totalUses    Int?           @map("total_uses")',
  '  benefitsJson Json?          @map("benefits_json")',
  '  status       ServiceStatus  @default(ACTIVE)',
  '  createdAt    DateTime       @default(now()) @map("created_at")',
  '',
  '  merchant            Merchant             @relation(fields: [merchantId], references: [id], onDelete: Cascade)',
  '  customerMemberships CustomerMembership[]',
  '',
  '  @@index([merchantId])',
  '  @@index([merchantId, status])',
  '  @@map("memberships")',
  '}',
  '',
  'model CustomerMembership {',
  '  id             String           @id @default(cuid())',
  '  customerId     String           @map("customer_id")',
  '  membershipId   String           @map("membership_id")',
  '  startAt        DateTime         @map("start_at")',
  '  endAt          DateTime?        @map("end_at")',
  '  remainingUses  Int?             @map("remaining_uses")',
  '  status         MembershipStatus @default(ACTIVE)',
  '  createdAt      DateTime         @default(now()) @map("created_at")',
  '',
  '  customer   Customer   @relation(fields: [customerId], references: [id], onDelete: Cascade)',
  '  membership Membership @relation(fields: [membershipId], references: [id])',
  '',
  '  @@index([customerId])',
  '  @@index([membershipId])',
  '  @@index([customerId, status])',
  '  @@map("customer_memberships")',
  '}',
  '',
  'model AppConfig {',
  '  id              String       @id @default(cuid())',
  '  merchantId      String       @unique @map("merchant_id")',
  '  modulesEnabled  Json         @map("modules_enabled")',
  '  homepageLayout  String       @default("service-first") @map("homepage_layout")',
  '  industrySkin    String       @default("generic") @map("industry_skin")',
  '  checkoutMode    CheckoutMode @default(SINGLE) @map("checkout_mode")',
  '  enableCoupon    Boolean      @default(false) @map("enable_coupon")',
  '  enableA2uReward Boolean      @default(false) @map("enable_a2u_reward")',
  '  createdAt       DateTime     @default(now()) @map("created_at")',
  '  updatedAt       DateTime     @updatedAt @map("updated_at")',
  '',
  '  merchant Merchant @relation(fields: [merchantId], references: [id], onDelete: Cascade)',
  '',
  '  @@map("app_configs")',
  '}'
];

const targetPath = path.join('D:\\', 'PiMerchantFramework', 'prisma', 'schema.prisma');
const schemaContent = schemaLines.join('\n') + '\n';

// 1 & 2. Node.js 脚本，直接用 utf8 写（不带 BOM），且只用 \\n
fs.writeFileSync(targetPath, schemaContent, { encoding: 'utf8' });

// 5. 写完读取验证
const buf = fs.readFileSync(targetPath);
const isBom = buf[0] === 0xEF && buf[1] === 0xBB && buf[2] === 0xBF;

// 3. 打印 OK 等信息
console.log(`OK: ${buf.length} bytes written, BOM: ${isBom}`);
