const fs = require('fs');
const path = require('path');

const pageLines = [
  "import PiLoginButton from '@/components/PiLoginButton';",
  "import Link from 'next/link';",
  "",
  "async function getServices() {",
  "  return [",
  "    { id: 'mock-uuid-1', title: '基础美甲护理', price: 5.0, description: '基础透明美甲，含手部护理，快速便捷且持久闪亮。' },",
  "    { id: 'mock-uuid-2', title: '高级光疗美甲', price: 12.0, description: '采用高级环保光疗胶，色彩饱和度高，持久不脱落，彰显优雅气质。' },",
  "    { id: 'mock-uuid-3', title: '日式美睫嫁接', price: 18.0, description: '专业美睫嫁接，采用自然仿真睫毛，打造清透素颜感。' },",
  "    { id: 'mock-uuid-4', title: '全套手足尊享', price: 25.0, description: '从手部到足部的全套深层清洁及滋养，赠送精油舒缓按摩。' }",
  "  ];",
  "}",
  "",
  "export default async function HomePage() {",
  "  const services = await getServices();",
  "",
  "  return (",
  "    <main className=\"min-h-screen bg-gradient-to-br from-[#1E112A] via-[#2A1642] to-[#110B19] text-gray-100 font-sans selection:bg-[#F3C136] selection:text-[#1E112A]\">",
  "      {/* 顶部导航 */}",
  "      <header className=\"sticky top-0 z-50 bg-[#1E112A]/80 backdrop-blur-lg border-b border-white/5 shadow-lg\">",
  "        <div className=\"max-w-4xl mx-auto flex justify-between items-center px-4 py-4 md:px-6\">",
  "          <div className=\"flex items-center space-x-3\">",
  "            <div className=\"w-10 h-10 rounded-xl bg-gradient-to-tr from-[#F3C136] to-[#FABC3D] p-[2px] shadow-lg shadow-[#F3C136]/20\">",
  "              <div className=\"flex items-center justify-center w-full h-full bg-[#1E112A] rounded-[10px]\">",
  "                <span className=\"text-xl font-black text-[#F3C136]\">M</span>",
  "              </div>",
  "            </div>",
  "            <div>",
  "              <h1 className=\"text-lg md:text-xl font-bold text-white tracking-tight\">美丽时光工作室</h1>",
  "              <p className=\"text-xs text-[#F3C136]/80 font-medium\">官方认证 Pi 商户</p>",
  "            </div>",
  "          </div>",
  "          <div className=\"bg-white/5 p-1 rounded-xl border border-white/10\">",
  "            <PiLoginButton />",
  "          </div>",
  "        </div>",
  "      </header>",
  "",
  "      {/* 头部欢迎墙 */}",
  "      <section className=\"max-w-4xl mx-auto px-4 py-10 md:py-16 md:px-6\">",
  "        <div className=\"text-center md:text-left\">",
  "          <h2 className=\"text-3xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-400 mb-4 tracking-tight leading-tight\">",
  "            焕发您的独特光彩 <br />",
  "            <span className=\"text-transparent bg-clip-text bg-gradient-to-r from-[#F3C136] to-[#EEA834]\">探索我们的优质服务</span>",
  "          </h2>",
  "          <p className=\"text-gray-400 text-sm md:text-base max-w-xl mx-auto md:mx-0 leading-relaxed\">",
  "            在美丽时光工作室，我们为您提供最专业的美容及美甲体验。<br className=\"hidden md:block\"/> 全面支持 Pi Network 链上安全支付。",
  "          </p>",
  "        </div>",
  "      </section>",
  "",
  "      {/* 服务列表 (Grid) */}",
  "      <section className=\"max-w-4xl mx-auto px-4 pb-16 md:px-6\">",
  "        <div className=\"grid grid-cols-1 md:grid-cols-2 gap-6\">",
  "          {services.map((service, index) => (",
  "            <div ",
  "              key={service.id} ",
  "              className=\"group bg-[#2A1642]/50 border border-white/10 rounded-3xl overflow-hidden hover:border-[#F3C136]/40 hover:bg-[#2F1948] transition-all duration-300 shadow-xl shadow-black/20 backdrop-blur-sm flex flex-col\"",
  "            >",
  "              {/* 封面色块 */}",
  "              <div className={`h-24 w-full bg-gradient-to-r ${index % 2 === 0 ? 'from-[#9333EA]/50 to-[#DB2777]/50' : 'from-[#2563EB]/50 to-[#7C3AED]/50'}`}></div>",
  "              ",
  "              <div className=\"p-6 flex-1 flex flex-col -mt-8\">",
  "                <div className=\"bg-[#1E112A] border border-white/10 rounded-2xl p-4 shadow-xl mb-4 transform group-hover:-translate-y-1 transition-transform self-start\">",
  "                  <span className=\"block text-xs font-bold text-gray-400 uppercase tracking-widest mb-1\">服务价格</span>",
  "                  <span className=\"text-3xl font-black text-[#F3C136]\">π {service.price.toFixed(2)}</span>",
  "                </div>",
  "                ",
  "                <h3 className=\"font-bold text-white text-xl mb-3 group-hover:text-[#F3C136] transition-colors\">",
  "                  {service.title}",
  "                </h3>",
  "                ",
  "                <p className=\"text-gray-400 text-sm leading-relaxed mb-8 flex-1\">",
  "                  {service.description}",
  "                </p>",
  "                ",
  "                <Link ",
  "                  href={`/services/${service.id}`}",
  "                  className=\"block w-full text-center font-bold text-[#1E112A] bg-[#F3C136] hover:bg-[#EEA834] py-3.5 rounded-xl transition-all shadow-[0_0_15px_rgba(243,193,54,0.3)] hover:shadow-[0_0_25px_rgba(243,193,54,0.5)] transform hover:-translate-y-0.5\"",
  "                >",
  "                  立即预约",
  "                </Link>",
  "              </div>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      </section>",
  "",
  "      {/* 底部版权 */}",
  "      <footer className=\"border-t border-white/5 bg-[#110B19]/50 backdrop-blur-md\">",
  "        <div className=\"max-w-4xl mx-auto px-4 py-8 md:px-6 flex flex-col md:flex-row justify-between items-center\">",
  "          <p className=\"text-gray-500 text-sm mb-4 md:mb-0\">",
  "            © 2026 美丽时光工作室. All rights reserved.",
  "          </p>",
  "          <div className=\"flex items-center space-x-6 text-sm text-gray-400\">",
  "            <span className=\"hover:text-[#F3C136] transition-colors cursor-pointer\">服务协议</span>",
  "            <span className=\"hover:text-[#F3C136] transition-colors cursor-pointer\">隐私政策</span>",
  "            <span className=\"flex items-center\"><span className=\"text-[#F3C136] mr-1\">✦</span> Powered by Pi Merchant</span>",
  "          </div>",
  "        </div>",
  "      </footer>",
  "    </main>",
  "  );",
  "}"
];

const targetPath = path.join('D:\\', 'PiMerchantFramework', 'apps', 'web', 'src', 'app', 'page.tsx');
const fileContent = pageLines.join('\n') + '\n';

fs.writeFileSync(targetPath, fileContent, { encoding: 'utf8' });

console.log('OK: page.tsx aesthetic update written via script');
