import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { Trend, Rate } from 'k6/metrics';

export const options = {
  vus: 50,
  duration: '3m',
  thresholds: {
    http_req_duration: ['p(95)<500'],
    errors: ['rate<0.01'],
  },
};

const latTrend = new Trend('latency');
const errorRate = new Rate('errors');

// Mock token generated by `node scripts/generate-k6-token.js`
const MOCK_TOKEN =
  'eyJ1aWQiOiJrNl9sb2FkX3Rlc3RfdXNlciIsImV4cCI6MTc4NDA4MDYwN30.bZjMW__Wu7cpzF9fuNI-muob_rppqOQdalQZirKvLgM';

export function setup() {
  return { mockToken: MOCK_TOKEN };
}

export default function (data) {
  const headers = { Cookie: `pi_auth_token=${data.mockToken}` };
  // Allow bypassing rate limits in middleware for load testing
  headers['x-k6-bypass-rate-limit'] = '1';

  group('models and ai query', function () {
    const res1 = http.get('http://host.docker.internal:3000/api/v1/models', { headers });
    const ok1 = check(res1, { 'models 200': (r) => r.status === 200 });
    if (!ok1) {
      console.error(
        'models request failed',
        res1.status,
        res1.body ? res1.body.substring(0, 200) : ''
      );
    }

    const payload = JSON.stringify({ prompt: 'Hello from k6 load test' });
    const res2 = http.post('http://host.docker.internal:3000/api/ai/query', payload, {
      headers: {
        'Content-Type': 'application/json',
        Cookie: `pi_auth_token=${data.mockToken}`,
        'x-k6-bypass-rate-limit': '1',
      },
    });
    const ok = check(res2, { 'ai 200': (r) => r.status === 200 });
    if (!ok) {
      console.error('ai query failed', res2.status, res2.body ? res2.body.substring(0, 1000) : '');
    }

    latTrend.add(res2.timings.duration);
    if (!ok) errorRate.add(1);

    sleep(1);
  });
}
